apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nim-servicemonitor
  namespace: nim
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - nim
  selector:
    matchLabels:
      app.kubernetes.io/name: nim-llm
  endpoints:
    - port: http-openai
      path: /metrics
      interval: 15s
